version = 1
SPDX-PackageName = "nc IONOS"
SPDX-PackageSupplier = "STRATO GmbH"
SPDX-PackageDownloadLocation = "NOASSERTION"

[[annotations]]
path = ["composer.json", "composer.lock"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 STRATO GmbH"
SPDX-License-Identifier = "AGPL-3.0-or-later"
