<?php
$CONFIG = [
	'enabledPreviewProviders' => [
		'OC\Preview\BMP',
        'OC\Preview\GIF',
        'OC\Preview\JPEG',
        'OC\Preview\Krita',
        'OC\Preview\MarkDown',
        'OC\Preview\MP3',
        'OC\Preview\OpenDocument',
        'OC\Preview\PNG',
        'OC\Preview\TXT',
        'OC\Preview\XBitmap',
		'OC\Preview\PDF',
		'OC\Preview\SVG',
		'OC\Preview\Font',
		'OC\Preview\Bundled',
		'OC\Preview\MP3',
		'OC\Preview\Movie',
		'OC\Preview\MSOfficeDoc',
		'OC\Preview\MSOffice2007',
		'OC\Preview\MSOffice2003',
		'OC\Preview\Imaginary',
		'OC\Preview\ImaginaryPDF',
	],
	'preview_max_x' => 2048,
	'preview_max_y' => 2048,
	'jpeg_quality' => 60,
];
